image:
  repository: ghcr.io/wbattles/waiboard
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

service:
  type: ClusterIP
  port: 8000

persistence:
  enabled: false
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce
