apiVersion: v1
kind: Service
metadata:
  name: {{ include "waiboard.fullname" . }}
  labels:
    {{- include "waiboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    {{- include "waiboard.selectorLabels" . | nindent 4 }}
